language: python
python:
    - "3.5"
    - "3.5-dev"  # 3.5 development branch
    - "3.6"
    - "3.6-dev"  # 3.6 development branch
    - "3.7-dev"  # 3.7 development branch
install:
    - pip install codecov
# command to run tests
script:
    - python hostlist/unittest_hostlist.py
    - coverage run hostlist/unittest_hostlist.py
    - python setup.py sdist bdist_wheel
    - pip install dist/py_hostlist-0.0.1.dev0-py2.py3-none-any.whl
    - hostlist -h
after_success:
    - codecov
